### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by reynoldscem** [jinyeying/FogRemoval#1]
Will pretrained model be made available?

**Comment by qiu-pinggaizi** [comment]
https://github.com/jinyeying/FogRemoval/blob/main/baseline_sup_adv_hz0.01_ft_nomask_Kres_ref_gray_moredata/models/checkpoint.1000.ckpt
这个模型是空的呀？

**Comment by qiu-pinggaizi** [comment]
https://github.com/jinyeying/FogRemoval/blob/main/baseline_sup_adv_hz0.01_ft_nomask_Kres_ref_gray_moredata/models/checkpoint.1000.ckpt 
the model is none of this url?

**Comment by qiu-pinggaizi** [comment]
@reynoldscem @jinyeying

**Comment by reynoldscem** [comment]
Ah yes @qiu-pinggaizi the file is empty.

@jinyeying was it perhaps an LFS file that hasn't synced with github properly or something?

**Comment by jinyeying** [comment]
> https://github.com/jinyeying/FogRemoval/blob/main/baseline_sup_adv_hz0.01_ft_nomask_Kres_ref_gray_moredata/models/checkpoint.1000.ckpt the model is none of this url?

then I provide the link of the checkpoints
https://www.dropbox.com/s/mrbeccbotj927xd/checkpoint.1000.ckpt?dl=0

**Comment by jinyeying** [comment]
> Ah yes @qiu-pinggaizi the file is empty.
> 
> @jinyeying was it perhaps an LFS file that hasn't synced with github properly or something?

then I provide the link of the checkpoints
https://www.dropbox.com/s/mrbeccbotj927xd/checkpoint.1000.ckpt?dl=0

**Comment by qiu-pinggaizi** [comment]
https://www.dropbox.com/s/mrbeccbotj927xd/checkpoint.1000.ckpt?dl=0
This link failed to download. Can you provide a download address of Baidu online disk @jinyeying
