### ISSUE TITLE
Training Setting Question

### ISSUE THREAD

**Issue by cuiziteng** [jinyeying/FogRemoval#10]
Thanks for the nice work. 

I'm confuse about the training setting in paper, which dataset have you use to first "pre-train" the model? 

And then use the "pre-train" weights to fine-tune on various dehazing dataset (like the smoke dataset)? Am I understand right ?

Hope to get your reply! Thx ~

**Comment by jinyeying** [comment]
> Thanks for the nice work.
> 
> I'm confuse about the training setting in paper, which dataset have you use to first "pre-train" the model?
> 
> And then use the "pre-train" weights to fine-tune on various dehazing dataset (like the smoke dataset)? Am I understand right ?
> 
> Hope to get your reply! Thx ~

yes, we use Fig. 7 and Fig. 8 in the supply to first "pre-train", then fine-tune on each datasets.

**Comment by cuiziteng** [comment]
Thanks for the explanation, I'll follow that setting.
