### ISSUE TITLE
Uncertainty Map

### ISSUE THREAD

**Issue by LongweiDing** [jinyeying/FogRemoval#12]
The generation illustration of Uncertainty Map is unclear in paper. More specifically, I cannot understand the paramater "theta". The paper just told it is the variance of the Laplace distribution without more information. If I want to train, how to get "theta"?
Can you provide more details?

**Comment by jinyeying** [comment]
> The generation illustration of Uncertainty Map is unclear in paper. More specifically, I cannot understand the paramater "theta". The paper just told it is the variance of the Laplace distribution without more information. If I want to train, how to get "theta"? Can you provide more details?

Sorry for the late reply. The uncertainty part is from “Uncertainty-driven loss for single image super-resolution”, the "theta" is based on
![image](https://github.com/user-attachments/assets/85d2e79f-bf0b-4fe0-9dc3-450ca717e204)

**Comment by jinyeying** [comment]
> The generation illustration of Uncertainty Map is unclear in paper. More specifically, I cannot understand the paramater "theta". The paper just told it is the variance of the Laplace distribution without more information. If I want to train, how to get "theta"? Can you provide more details?

Each value in the uncertainty map represents the confidence of the defogging operation at the corresponding pixel (i.e. the variance). The higher the value, the more uncertain the network's prediction for that pixel. We assume the estimated defogged value follows a Laplace distribution relative to the ground truth. In Fig. 5, the decoder generates the uncertainty map $\theta$, updated with the loss in Eq.(5).
We use the uncertainty map to identify the dense fog regions.
