### ISSUE TITLE
Dataset mirror

### ISSUE THREAD

**Issue by shachargluska** [jinyeying/FogRemoval#13]
Hi,
Thank you for your work. Unfortunately, the dropbox link look broken to me.
Is there another way to get the data?

Thanks in advance!

**Comment by jinyeying** [comment]
> Hi, Thank you for your work. Unfortunately, the dropbox link look broken to me. Is there another way to get the data?
> 
> Thanks in advance!

thanks for your interest, I think I wrongly delete something. I will fix it as soon as possible and let you know.

**Comment by jinyeying** [comment]
> 

Now it is available!
