### ISSUE TITLE
output image is strange

### ISSUE THREAD

**Issue by 2bhuanleduo** [jinyeying/FogRemoval#3]
Sorry to bother. I use your code to work on my own real-world image and found my output is very strange, but when I use test images in directory provided it shows normal. So can you tell me how to deal with it ?
My output image url : https://github.com/2bhuanleduo/git-demo/blob/master/2_25.png

**Comment by hdcxqrc** [comment]
Where is test datase（12pairs）?

**Comment by jinyeying** [comment]
> Sorry to bother. I use your code to work on my own real-world image and found my output is very strange, but when I use test images in directory provided it shows normal. So can you tell me how to deal with it ? My output image url : https://github.com/2bhuanleduo/git-demo/blob/master/2_25.png
Maybe you can try:
python main_test.py --datasetpath [path_to_NH-HAZE dataset]

**Comment by jinyeying** [comment]
https://www.dropbox.com/home/badweather/ACCV2022_defog/Dataset_day/Smoke
