### ISSUE TITLE
Test dataset

### ISSUE THREAD

**Issue by hdcxqrc** [jinyeying/FogRemoval#5]
Where is test datase（12pairs）?

**Comment by jinyeying** [comment]
> Where is test datase（12pairs）?

https://www.dropbox.com/sh/idkg762ni884gpi/AACBfFJMepnNzW0J2N-e_Upja?dl=0

**Comment by hdcxqrc** [comment]
Some clear images in train sets are haze, such as 83.png, 84.png, 24.png and 24.png

**Comment by jinyeying** [comment]
> 

Thanks for pointing it out.
