### ISSUE TITLE
Comparsioins

### ISSUE THREAD

**Issue by hdcxqrc** [jinyeying/FogRemoval#6]
Can you give other results of comparsions, such as MSBDN, PSD and Dehamer.

**Comment by jinyeying** [comment]
https://www.dropbox.com/sh/nsbqnou4hqkeh1s/AAAkCKQVWdgR4WxOR-zRM16Aa?dl=0

Above is the baseline results.

**Comment by hdcxqrc** [comment]
Can you provide the evaluation metrics (psnr, ssim) of the whole baselines?

**Comment by hdcxqrc** [comment]
Did you train the network of comparsions on the smoke dataset?

**Comment by hdcxqrc** [comment]
I just train the MSBDN 16 epochs, then the psnr is16.66 and ssim is 0.4263

**Comment by jinyeying** [comment]
see [psnr_ssim_all.m](https://github.com/jinyeying/FogRemoval/blob/main/psnr_ssim_all.m)

**Comment by hdcxqrc** [comment]
Did you train the network of comparsions on the smoke dataset?  but you train your network on the smoke dataset. Whether such a comparative experiment is convincing?
