### ISSUE TITLE
comparsions

### ISSUE THREAD

**Issue by RC-Qiao** [jinyeying/FogRemoval#7]
Did you train the network of comparsions on the smoke dataset? but you train your network on the smoke dataset. Whether such a comparative experiment is convincing?

**Comment by jinyeying** [comment]
> Whole visual Results of comparisons on NH-Haze ，Dense-Haze and O-haze testing set.

We can only release our results on NH-Haze, Dense-Haze and O-haze testing sets. We cannot release other baselines results.
