### ISSUE TITLE
Weights for pretrained model

### ISSUE THREAD

**Issue by SDMMG** [jinyeying/FogRemoval#9]
Hi! First of all, thanks for your work, it seems really interesting to me. I'm trying to test your model on some images of SMOKE Dataset loading "checkpoint.1000.ckpt", but it appears to be empty. Would it be possible to update the weights or download them another way to test the model?

Thanks in advance.

**Comment by jinyeying** [comment]
> Hi! First of all, thanks for your work, it seems really interesting to me. I'm trying to test your model on some images of SMOKE Dataset loading "checkpoint.1000.ckpt", but it appears to be empty. Would it be possible to update the weights or download them another way to test the model?
> 
> Thanks in advance.

update the weights and testing code
